# during_game
#   during
#       check_end_game
#       draw_playing_window
#   enemy_turn
#       check_player_hit
#       check_space
#       blind_guess
#       find_hits
#       enemy_turn
#   player_turn
#       check_enemy_hit
#       player_turn
#   scores
#       draw_enemy_score
#       draw_player_score
#   valid
#       valid_player_space
#       valid_guess
